// Copyright 2025 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

#ifndef SRC_ERRORS_H_
#define SRC_ERRORS_H_

#define SQLITE_ERROR_ENUM(V)        \
  V(SQLITE_ERROR)                   \
  V(SQLITE_INTERNAL)                \
  V(SQLITE_PERM)                    \
  V(SQLITE_ABORT)                   \
  V(SQLITE_BUSY)                    \
  V(SQLITE_LOCKED)                  \
  V(SQLITE_NOMEM)                   \
  V(SQLITE_READONLY)                \
  V(SQLITE_INTERRUPT)               \
  V(SQLITE_IOERR)                   \
  V(SQLITE_CORRUPT)                 \
  V(SQLITE_NOTFOUND)                \
  V(SQLITE_FULL)                    \
  V(SQLITE_CANTOPEN)                \
  V(SQLITE_PROTOCOL)                \
  V(SQLITE_EMPTY)                   \
  V(SQLITE_SCHEMA)                  \
  V(SQLITE_TOOBIG)                  \
  V(SQLITE_CONSTRAINT)              \
  V(SQLITE_MISMATCH)                \
  V(SQLITE_MISUSE)                  \
  V(SQLITE_NOLFS)                   \
  V(SQLITE_AUTH)                    \
  V(SQLITE_FORMAT)                  \
  V(SQLITE_RANGE)                   \
  V(SQLITE_NOTADB)                  \
  V(SQLITE_NOTICE)                  \
  V(SQLITE_WARNING)                 \
  V(SQLITE_ROW)                     \
  V(SQLITE_DONE)                    \
  V(SQLITE_ERROR_MISSING_COLLSEQ)   \
  V(SQLITE_ERROR_RETRY)             \
  V(SQLITE_ERROR_SNAPSHOT)          \
  V(SQLITE_IOERR_READ)              \
  V(SQLITE_IOERR_SHORT_READ)        \
  V(SQLITE_IOERR_WRITE)             \
  V(SQLITE_IOERR_FSYNC)             \
  V(SQLITE_IOERR_DIR_FSYNC)         \
  V(SQLITE_IOERR_TRUNCATE)          \
  V(SQLITE_IOERR_FSTAT)             \
  V(SQLITE_IOERR_UNLOCK)            \
  V(SQLITE_IOERR_RDLOCK)            \
  V(SQLITE_IOERR_DELETE)            \
  V(SQLITE_IOERR_BLOCKED)           \
  V(SQLITE_IOERR_NOMEM)             \
  V(SQLITE_IOERR_ACCESS)            \
  V(SQLITE_IOERR_CHECKRESERVEDLOCK) \
  V(SQLITE_IOERR_LOCK)              \
  V(SQLITE_IOERR_CLOSE)             \
  V(SQLITE_IOERR_DIR_CLOSE)         \
  V(SQLITE_IOERR_SHMOPEN)           \
  V(SQLITE_IOERR_SHMSIZE)           \
  V(SQLITE_IOERR_SHMLOCK)           \
  V(SQLITE_IOERR_SHMMAP)            \
  V(SQLITE_IOERR_SEEK)              \
  V(SQLITE_IOERR_DELETE_NOENT)      \
  V(SQLITE_IOERR_MMAP)              \
  V(SQLITE_IOERR_GETTEMPPATH)       \
  V(SQLITE_IOERR_CONVPATH)          \
  V(SQLITE_IOERR_VNODE)             \
  V(SQLITE_IOERR_AUTH)              \
  V(SQLITE_IOERR_BEGIN_ATOMIC)      \
  V(SQLITE_IOERR_COMMIT_ATOMIC)     \
  V(SQLITE_IOERR_ROLLBACK_ATOMIC)   \
  V(SQLITE_IOERR_DATA)              \
  V(SQLITE_IOERR_CORRUPTFS)         \
  V(SQLITE_IOERR_IN_PAGE)           \
  V(SQLITE_LOCKED_SHAREDCACHE)      \
  V(SQLITE_LOCKED_VTAB)             \
  V(SQLITE_BUSY_RECOVERY)           \
  V(SQLITE_BUSY_SNAPSHOT)           \
  V(SQLITE_BUSY_TIMEOUT)            \
  V(SQLITE_CANTOPEN_NOTEMPDIR)      \
  V(SQLITE_CANTOPEN_ISDIR)          \
  V(SQLITE_CANTOPEN_FULLPATH)       \
  V(SQLITE_CANTOPEN_CONVPATH)       \
  V(SQLITE_CANTOPEN_DIRTYWAL)       \
  V(SQLITE_CANTOPEN_SYMLINK)        \
  V(SQLITE_CORRUPT_VTAB)            \
  V(SQLITE_CORRUPT_SEQUENCE)        \
  V(SQLITE_CORRUPT_INDEX)           \
  V(SQLITE_READONLY_RECOVERY)       \
  V(SQLITE_READONLY_CANTLOCK)       \
  V(SQLITE_READONLY_ROLLBACK)       \
  V(SQLITE_READONLY_DBMOVED)        \
  V(SQLITE_READONLY_CANTINIT)       \
  V(SQLITE_READONLY_DIRECTORY)      \
  V(SQLITE_ABORT_ROLLBACK)          \
  V(SQLITE_CONSTRAINT_CHECK)        \
  V(SQLITE_CONSTRAINT_COMMITHOOK)   \
  V(SQLITE_CONSTRAINT_FOREIGNKEY)   \
  V(SQLITE_CONSTRAINT_FUNCTION)     \
  V(SQLITE_CONSTRAINT_NOTNULL)      \
  V(SQLITE_CONSTRAINT_PRIMARYKEY)   \
  V(SQLITE_CONSTRAINT_TRIGGER)      \
  V(SQLITE_CONSTRAINT_UNIQUE)       \
  V(SQLITE_CONSTRAINT_VTAB)         \
  V(SQLITE_CONSTRAINT_ROWID)        \
  V(SQLITE_CONSTRAINT_PINNED)       \
  V(SQLITE_CONSTRAINT_DATATYPE)     \
  V(SQLITE_NOTICE_RECOVER_WAL)      \
  V(SQLITE_NOTICE_RECOVER_ROLLBACK) \
  V(SQLITE_NOTICE_RBU)              \
  V(SQLITE_WARNING_AUTOINDEX)       \
  V(SQLITE_AUTH_USER)               \
  V(SQLITE_OK_LOAD_PERMANENTLY)     \
  V(SQLITE_OK_SYMLINK)

#endif  // SRC_ERRORS_H_
